/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Espace_Patient.patient_home;
import Login.admin_login;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Login.login_Home;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static public_var.variables.*;

/**
 *
 * @author berich
 */
public class patient_login extends javax.swing.JFrame {
    
     public static String idf;
     
      public ArrayList<ImageIcon> images = new ArrayList<ImageIcon>();
    String[] location =new String[25];

    /**
     * Creates new form admin_login
     */
    public patient_login() {
        initComponents();
     location[0]="/plateforme_cancer_du_poumon/images/animation/textbox_user_1.jpg";
         location[1]="/plateforme_cancer_du_poumon/images/animation/textbox_user_2.jpg";
         location[2]="/plateforme_cancer_du_poumon/images/animation/textbox_user_4.jpg";
         location[3]="/plateforme_cancer_du_poumon/images/animation/textbox_user_5.jpg";
         location[4]="/plateforme_cancer_du_poumon/images/animation/textbox_user_6.jpg";
         location[5]="/plateforme_cancer_du_poumon/images/animation/textbox_user_7.jpg";
         location[6]="/plateforme_cancer_du_poumon/images/animation/textbox_user_8.jpg";
         location[7]="/plateforme_cancer_du_poumon/images/animation/textbox_user_9.jpg";
         location[8]="/plateforme_cancer_du_poumon/images/animation/textbox_user_10.jpg";
         location[9]="/plateforme_cancer_du_poumon/images/animation/textbox_user_11.jpg";
         location[10]="/plateforme_cancer_du_poumon/images/animation/textbox_user_13.jpg";
         location[11]="/plateforme_cancer_du_poumon/images/animation/textbox_user_14.jpg";
         location[12]="/plateforme_cancer_du_poumon/images/animation/textbox_user_15.jpg";
         location[13]="/plateforme_cancer_du_poumon/images/animation/textbox_user_16.jpg";
         location[14]="/plateforme_cancer_du_poumon/images/animation/textbox_user_17.jpg";
         location[15]="/plateforme_cancer_du_poumon/images/animation/textbox_user_18.jpg";
         location[16]="/plateforme_cancer_du_poumon/images/animation/textbox_user_19.jpg";
         location[17]="/plateforme_cancer_du_poumon/images/animation/textbox_user_20.jpg";
         location[18]="/plateforme_cancer_du_poumon/images/animation/textbox_user_21.jpg";
         location[19]="/plateforme_cancer_du_poumon/images/animation/textbox_user_22.jpg";
         location[20]="/plateforme_cancer_du_poumon/images/animation/textbox_user_23.jpg";
         location[21]="/plateforme_cancer_du_poumon/images/animation/textbox_user_24.jpg";
         Diapo();
        
    
       cnx= DB_Connexion.Connexion();
    }
    
    private void Diapo()
    {
        for(int i=0;i<23;i++){
        ImageIcon imge = new ImageIcon(location[i]);  
        images.add(imge);
     
        }
        ImageIcon imf = new ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/animation/textbox_user_24.jpg"));
        images.add(imf);
        
    }
    
   
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        image = new javax.swing.JLabel();
        textlogin = new rojerusan.RSMetroTextFullPlaceHolder();
        password = new rojerusan.RSMetroTextPassPlaceHolderView();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/icons8_User_48px_7.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/icons8_Lock_50px_2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(3, 182, 215));
        jLabel4.setText(" Espace Patient");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("___________________________________________________");

        rSButtonMetro1.setBackground(new java.awt.Color(3, 182, 215));
        rSButtonMetro1.setText("Connexion");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/animation/debut.png"))); // NOI18N
        image.setFocusable(false);
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });

        textlogin.setForeground(new java.awt.Color(3, 182, 215));
        textlogin.setBorderColor(new java.awt.Color(3, 182, 215));
        textlogin.setBotonColor(new java.awt.Color(3, 182, 215));
        textlogin.setPhColor(new java.awt.Color(3, 182, 215));
        textlogin.setPlaceholder("Identifiant");
        textlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textloginKeyPressed(evt);
            }
        });

        password.setForeground(new java.awt.Color(3, 182, 215));
        password.setBorderColor(new java.awt.Color(3, 182, 215));
        password.setBotonColor(new java.awt.Color(3, 182, 215));
        password.setPhColor(new java.awt.Color(3, 182, 215));
        password.setPlaceholder("Mot de passe");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(image)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(textlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        //jPanel1.setBackground(new Color(255,255,255,160));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(850, 70, 380, 520);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/icons8_Logout_Rounded_Left_50px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/INTERPATIENT_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1600, 1102));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1594, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String recuperer(){
        return idf ;
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.hide();
        login_Home h = new  login_Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
         // TODO add your handling code here:
        String rqt =" select * from patient where patient_identifiant = ? and patient_password = ? " ;
        try{
            ps = cnx.prepareStatement(rqt);
            ps.setString(1, textlogin.getText()); idf=textlogin.getText();
            ps.setString(2, String.valueOf(password.getPassword()));
            rs = ps.executeQuery();
        if(rs.next()){
          setVisible(false);
          new patient_home().setVisible(true);               
        }else { JOptionPane.showMessageDialog(this, "identifiant ou mot de passe incorrect");
        textlogin.setText("");
        password.setText("");}
                ps.close();
                rs.close();
                
        }catch(SQLException e){
           Logger.getLogger(patient_login.class.getName()).log(Level.SEVERE ,null,e);
           
    }                                       
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked

    }//GEN-LAST:event_imageMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
      ImageIcon imf = new ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/animation/textbox_password_1.png"));
        image.setIcon(imf);
    }//GEN-LAST:event_passwordKeyPressed

    private void textloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textloginKeyPressed
       ImageIcon imf = new ImageIcon(getClass().getResource("/plateforme_cancer_du_poumon/images/animation/debut.JPG"));
        image.setIcon(imf);
    }//GEN-LAST:event_textloginKeyPressed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private rojerusan.RSMetroTextPassPlaceHolderView password;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojerusan.RSMetroTextFullPlaceHolder textlogin;
    // End of variables declaration//GEN-END:variables
}
