/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Espace_Admin;

/**
 *
 * @author berich
 */
public class infos_patient extends javax.swing.JFrame {

    /**
     * Creates new form infos_patient
     */
    public infos_patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patient_infos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        image = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        onco = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        date_naiss = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        sexe = new javax.swing.JLabel();
        sit_fam = new javax.swing.JLabel();
        gsang = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        code_assurance = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tlf = new javax.swing.JLabel();
        wilaya = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        numdoss = new javax.swing.JLabel();
        dateins = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        mat = new javax.swing.JLabel();
        pneu = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        patient_infos.setBackground(new java.awt.Color(228, 241, 254));
        patient_infos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 18), new java.awt.Color(3, 182, 215))); // NOI18N
        patient_infos.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(3, 182, 215));
        jLabel8.setText("Nom :");
        patient_infos.add(jLabel8);
        jLabel8.setBounds(50, 250, 73, 20);

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 182, 215));
        jLabel9.setText("Prenom :");
        patient_infos.add(jLabel9);
        jLabel9.setBounds(430, 250, 89, 20);

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 182, 215));
        jLabel10.setText("Date de Naissance :");
        patient_infos.add(jLabel10);
        jLabel10.setBounds(50, 300, 159, 20);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(3, 182, 215));
        jLabel11.setText("Sexe :");
        patient_infos.add(jLabel11);
        jLabel11.setBounds(50, 350, 140, 21);

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(3, 182, 215));
        jLabel12.setText("Situation Familliale :");
        patient_infos.add(jLabel12);
        jLabel12.setBounds(50, 410, 170, 30);

        jLabel13.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(3, 182, 215));
        jLabel13.setText("Adresse :");
        patient_infos.add(jLabel13);
        jLabel13.setBounds(50, 470, 99, 28);

        jLabel14.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(3, 182, 215));
        jLabel14.setText("Wilaya :");
        patient_infos.add(jLabel14);
        jLabel14.setBounds(430, 470, 67, 20);

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 182, 215));
        jLabel15.setText("Email :");
        patient_infos.add(jLabel15);
        jLabel15.setBounds(50, 540, 90, 19);

        jLabel16.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(3, 182, 215));
        jLabel16.setText("Télephone :");
        patient_infos.add(jLabel16);
        jLabel16.setBounds(430, 530, 96, 26);

        jLabel22.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(3, 182, 215));
        jLabel22.setText("Groupe Sanguin :");
        patient_infos.add(jLabel22);
        jLabel22.setBounds(430, 360, 144, 20);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Espace_Admin/sem_foto.jpg"))); // NOI18N
        jScrollPane3.setViewportView(image);

        patient_infos.add(jScrollPane3);
        jScrollPane3.setBounds(50, 30, 190, 190);

        jLabel18.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 182, 215));
        jLabel18.setText("Code d'assurance:");
        patient_infos.add(jLabel18);
        jLabel18.setBounds(430, 410, 147, 23);

        jLabel19.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 182, 215));
        jLabel19.setText("Date d'inscription:");
        patient_infos.add(jLabel19);
        jLabel19.setBounds(430, 30, 170, 30);

        jLabel20.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(3, 182, 215));
        jLabel20.setText("Age :");
        patient_infos.add(jLabel20);
        jLabel20.setBounds(430, 300, 73, 20);

        onco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        onco.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(onco);
        onco.setBounds(600, 200, 190, 30);

        nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nom.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(nom);
        nom.setBounds(220, 240, 190, 30);

        prenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prenom.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(prenom);
        prenom.setBounds(600, 240, 190, 30);

        date_naiss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date_naiss.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(date_naiss);
        date_naiss.setBounds(220, 290, 190, 30);

        age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        age.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(age);
        age.setBounds(600, 290, 190, 30);

        sexe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sexe.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(sexe);
        sexe.setBounds(220, 350, 190, 30);

        sit_fam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sit_fam.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(sit_fam);
        sit_fam.setBounds(220, 410, 190, 30);

        gsang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gsang.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(gsang);
        gsang.setBounds(600, 350, 190, 30);

        address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        address.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(address);
        address.setBounds(220, 470, 190, 30);

        code_assurance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        code_assurance.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(code_assurance);
        code_assurance.setBounds(600, 400, 190, 30);

        email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(email);
        email.setBounds(220, 530, 190, 30);

        tlf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tlf.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(tlf);
        tlf.setBounds(590, 520, 190, 30);

        wilaya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wilaya.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(wilaya);
        wilaya.setBounds(600, 460, 190, 30);
        patient_infos.add(jSeparator4);
        jSeparator4.setBounds(10, 238, 780, 10);
        patient_infos.add(jSeparator1);
        jSeparator1.setBounds(50, 280, 360, 2);
        patient_infos.add(jSeparator2);
        jSeparator2.setBounds(50, 332, 360, 10);
        patient_infos.add(jSeparator3);
        jSeparator3.setBounds(50, 390, 360, 2);
        patient_infos.add(jSeparator5);
        jSeparator5.setBounds(50, 450, 0, 2);
        patient_infos.add(jSeparator6);
        jSeparator6.setBounds(50, 450, 360, 2);
        patient_infos.add(jSeparator7);
        jSeparator7.setBounds(50, 512, 360, 10);
        patient_infos.add(jSeparator8);
        jSeparator8.setBounds(50, 572, 370, 0);
        patient_infos.add(jSeparator9);
        jSeparator9.setBounds(50, 570, 360, 2);
        patient_infos.add(jSeparator10);
        jSeparator10.setBounds(430, 282, 370, 0);
        patient_infos.add(jSeparator11);
        jSeparator11.setBounds(430, 332, 370, 0);
        patient_infos.add(jSeparator12);
        jSeparator12.setBounds(430, 390, 370, 2);
        patient_infos.add(jSeparator13);
        jSeparator13.setBounds(430, 452, 370, 0);
        patient_infos.add(jSeparator14);
        jSeparator14.setBounds(440, 510, 360, 0);
        patient_infos.add(jSeparator15);
        jSeparator15.setBounds(430, 570, 370, 2);

        jLabel21.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(3, 182, 215));
        jLabel21.setText("Oncologue .R:");
        patient_infos.add(jLabel21);
        jLabel21.setBounds(430, 210, 150, 20);

        jLabel23.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(3, 182, 215));
        jLabel23.setText("N° dossier médical :");
        patient_infos.add(jLabel23);
        jLabel23.setBounds(430, 80, 170, 28);
        patient_infos.add(jSeparator16);
        jSeparator16.setBounds(430, 70, 360, 2);
        patient_infos.add(jSeparator17);
        jSeparator17.setBounds(430, 112, 360, 10);
        patient_infos.add(jSeparator18);
        jSeparator18.setBounds(430, 162, 360, 2);

        numdoss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numdoss.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(numdoss);
        numdoss.setBounds(600, 80, 190, 30);

        dateins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateins.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(dateins);
        dateins.setBounds(600, 30, 190, 30);
        patient_infos.add(jSeparator19);
        jSeparator19.setBounds(430, 200, 360, 2);

        jLabel24.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(3, 182, 215));
        jLabel24.setText("identifiant:");
        patient_infos.add(jLabel24);
        jLabel24.setBounds(430, 120, 92, 30);

        jLabel25.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(3, 182, 215));
        jLabel25.setText("Pneumologue .R:");
        patient_infos.add(jLabel25);
        jLabel25.setBounds(430, 170, 150, 20);

        mat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mat.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(mat);
        mat.setBounds(600, 120, 190, 30);

        pneu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pneu.setForeground(new java.awt.Color(52, 73, 94));
        patient_infos.add(pneu);
        pneu.setBounds(600, 170, 190, 30);
        patient_infos.add(jSeparator20);
        jSeparator20.setBounds(430, 280, 360, 2);
        patient_infos.add(jSeparator21);
        jSeparator21.setBounds(430, 330, 360, 20);
        patient_infos.add(jSeparator22);
        jSeparator22.setBounds(430, 452, 360, 10);
        patient_infos.add(jSeparator23);
        jSeparator23.setBounds(430, 510, 360, 2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patient_infos, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patient_infos, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(824, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infos_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infos_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infos_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infos_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infos_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel address;
    public javax.swing.JLabel age;
    public javax.swing.JLabel code_assurance;
    public javax.swing.JLabel date_naiss;
    public javax.swing.JLabel dateins;
    public javax.swing.JLabel email;
    public javax.swing.JLabel gsang;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel mat;
    public javax.swing.JLabel nom;
    public javax.swing.JLabel numdoss;
    public javax.swing.JLabel onco;
    private javax.swing.JPanel patient_infos;
    public javax.swing.JLabel pneu;
    public javax.swing.JLabel prenom;
    public javax.swing.JLabel sexe;
    public javax.swing.JLabel sit_fam;
    public javax.swing.JLabel tlf;
    public javax.swing.JLabel wilaya;
    // End of variables declaration//GEN-END:variables
}
